name: Delete submodule branch on closed pr
on:
  push:
    # types: [closed]
    branches:
      - ATX-2519

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name.length > 10 }}
    steps:
      - name: delete branch
        run: |
          console.log("github context: ", github)
          console.log("context: ", context)
        # uses: SvanBoxel/delete-merged-branch@main
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}