name: Publish Package To GitHub Packages

on:
  pull_request:
    branches:
      - packages
    types: [closed]
  # push:
  #   branches:
  #     - "ATX-2363"
concurrency: ${{ github.workflow }}-${{ github.ref_name }}-packages

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          cache: "pnpm"

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: pnpm i
      - run: pnpm -r publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
